In [1]:
import numpy as np

In [16]:
#List 
a = [30,40,50]
b = [70,80,90]
print(a)
print(b)
print(type(a))
print(type(b))
print(a+b)
print(a,b)


[30, 40, 50]
[70, 80, 90]
<class 'list'>
<class 'list'>
[30, 40, 50, 70, 80, 90]
[30, 40, 50] [70, 80, 90]


In [27]:
#Numpy
a = np.array ([30,40,50])
b = np.array ([70,80,90])
print(a)
print(b)
print(type(a))
print(type(b))
print(a+b)
print(a-b)
print(a*b)

[30 40 50]
[70 80 90]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[100 120 140]
[-40 -40 -40]
[2100 3200 4500]


In [26]:
s = np.array([10,20,"30"])
print(s)
print(type(s))

['10' '20' '30']
<class 'numpy.ndarray'>


In [29]:
v = np.array([20,50,60.2])
print(v)
print(type(v))

[20.  50.  60.2]
<class 'numpy.ndarray'>


In [36]:
arr = np.array([[30,10,30],[20,50,60],[90,50,40]])
print(arr)
print(type(arr))

[[30 10 30]
 [20 50 60]
 [90 50 40]]
<class 'numpy.ndarray'>


Slicing😒😴😴