In [12]:
import numpy as np

In [16]:
#List 
a = [30,40,50]
b = [70,80,90]
print(a)
print(b)
print(type(a))
print(type(b))
print(a+b)
print(a,b)


[30, 40, 50]
[70, 80, 90]
<class 'list'>
<class 'list'>
[30, 40, 50, 70, 80, 90]
[30, 40, 50] [70, 80, 90]


In [27]:
#Numpy
a = np.array ([30,40,50])
b = np.array ([70,80,90])
print(a)
print(b)
print(type(a))
print(type(b))
print(a+b)
print(a-b)
print(a*b)

[30 40 50]
[70 80 90]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[100 120 140]
[-40 -40 -40]
[2100 3200 4500]


In [26]:
s = np.array([10,20,"30"])
print(s)
print(type(s))

['10' '20' '30']
<class 'numpy.ndarray'>


In [29]:
v = np.array([20,50,60.2])
print(v)
print(type(v))

[20.  50.  60.2]
<class 'numpy.ndarray'>


In [36]:
arr = np.array([[30,10,30],[20,50,60],[90,50,40]])
print(arr)
print(type(arr))

[[30 10 30]
 [20 50 60]
 [90 50 40]]
<class 'numpy.ndarray'>


Slicing😒😴😴

In [13]:
num = np.array([10,30,27,39])
print(num[0:3])
print(num[0:1])

[10 30 27]
[10]


In [16]:
a = np.array([[30,29,49,59,55],[43,58,34,71,21],[44,11,22,33,55]])
print(np.shape(a))
print(np.size(a))
print(type(a))

(3, 5)
15
<class 'numpy.ndarray'>


In [15]:
arr = np.array([[50,39,43,10,99],[20,22,39,34,88],[38,29,33,44,11]])
print(arr)
print(type(arr))


[[50 39 43 10 99]
 [20 22 39 34 88]
 [38 29 33 44 11]]
<class 'numpy.ndarray'>


In [30]:
arr = np.array([[50,39,43,10,99],[20,22,39,34,88],[38,29,33,44,11]])
print(arr[2,0:4])
print(arr[1,3])
print(np.size(arr))
print(np.ndim(arr))
print(arr.dtype)

[38 29 33 44]
34
15
2
int64


Inspecting An Array😍😒😴

In [31]:
import numpy as np

In [53]:
a = [[39,20,50],[30,59,40]]
arr = np.array(a)
print(arr)
print(type(arr)) #data type of variable
print(arr.shape) #rows, column
print(len(arr)) #number of nested values
print(arr.size) #number of elements
print(arr.dtype)  #data type of array
print(arr.astype(int)) #conversion of datatype


[[39 20 50]
 [30 59 40]]
<class 'numpy.ndarray'>
(2, 3)
2
6
int64
[[39 20 50]
 [30 59 40]]


Mathmetical Operations😍😍😒

In [54]:
import numpy as np

In [56]:
arr1 = np.array([[30,20,10,50],[40,20,70,60]])
arr2 = np.array([[30,20,10,50],[90,80,40,60]])
print(arr1+arr2)
print(np.add(arr1,arr2))

[[ 60  40  20 100]
 [130 100 110 120]]
[[ 60  40  20 100]
 [130 100 110 120]]


In [62]:
arr1 = np.array([[30,20,10,50],[40,20,70,60]])
arr2 = np.array([[30,20,10,50],[90,80,40,60]])
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1//arr2)
print(np.subtract(arr1,arr2))

[[  0   0   0   0]
 [-50 -60  30   0]]
[[ 900  400  100 2500]
 [3600 1600 2800 3600]]
[[1.         1.         1.         1.        ]
 [0.44444444 0.25       1.75       1.        ]]
[[1 1 1 1]
 [0 0 1 1]]
[[  0   0   0   0]
 [-50 -60  30   0]]


In [65]:
arr1 = np.array([3,7,9,13,17,19])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[  9  49  81 169 289 361]


In [74]:
arr1 = ([[9,49,81,169,289,361]])
print(np.sqrt(arr1))


[[ 3.  7.  9. 13. 17. 19.]]


Joint and Split Arrays🤗😍😍

In [75]:
a = [30,40,50]
b = [5,3,2,1]
print(a+b)

[30, 40, 50, 5, 3, 2, 1]


In [79]:
#Concatenate
import numpy as np

a = np.array([30,40,50])
b = np.array([5,3,2,1])
print(np.concatenate([a,b]))

[30 40 50  5  3  2  1]


In [84]:
a = np.array([[30,40],[50,10]])
b = np.array([[5,3],[2,1]])
print(np.concatenate([a,b], axis=1))

[[30 40  5  3]
 [50 10  2  1]]


In [88]:
print(np.hstack([a,b]))  # Horizontal Concatination
print(np.vstack([a,b]))  # Vertical concatination

[[30 40  5  3]
 [50 10  2  1]]
[[30 40]
 [50 10]
 [ 5  3]
 [ 2  1]]


In [94]:
a = np.array([[20,30,70,90],[40,50,10,80]])
b = np.array_split(a,2)
print(b)

[array([[20, 30, 70, 90]]), array([[40, 50, 10, 80]])]


Adding and Removing Elements in the Arrays😒😍😒

In [2]:
import numpy as np

In [6]:
a = np.array([20,30,40,50])
print(np.append(a,(22)))

[20 30 40 50 22]


In [7]:
a = np.array([11,22,33,44,55])
print(np.append(a,([1,2])))

[11 22 33 44 55  1  2]


In [8]:
print(a)

[11 22 33 44 55]


In [10]:
print(np.insert(a,2,101))   #array, index , value
print(np.insert(a,4,123))

[ 11  22 101  33  44  55]
[ 11  22  33  44 123  55]


In [21]:
s = np.array([[40,20,10],[90,80,70]])
print(np.insert(s,1,[400,500], axis = 1))

[[ 40 400  20  10]
 [ 90 500  80  70]]


In [28]:
print(s)
print()
print(np.delete(s,1, axis = 1))

[[40 20 10]
 [90 80 70]]

[[40 10]
 [90 70]]


Numpy - Sort, Filter and Search🤗😍😒

In [2]:
import numpy as np

In [36]:
arr = np.array([[3,1,4,12,45,5],[49,30,44,21,22,31]])
print(np.sort(arr))

[[ 1  3  4  5 12 45]
 [21 22 30 31 44 49]]


In [40]:
ar = np.array([30,22,33,45,50])
a = np.where(ar == 2)
print(a)

w = np.where(ar %2 == 0)
print(w)

(array([], dtype=int64),)
(array([0, 1, 4]),)


In [45]:
ab = np.array([5,1,2,3,4,5,6,7])
ag = np.searchsorted(ab,7)
print(ag)

7


In [46]:
ar = np.array([30,44,22,55,66])

vg = [True, False,True,True,False]

new = ar[vg]
print(new)

[30 22 55]


In [47]:
ar = np.array([30,44,22,55,66])

fa = ar>40 
new = ar[fa]
print(new)

[44 55 66]


Aggregating Functions in Numpy😒😒😍

In [54]:
abc = np.array([30,20,122,150,45,11])

print(np.max(abc))
print(np.min(abc))
print(np.mean(abc))
print(np.sum(abc))
print(np.cumsum(abc))
print(np.cumprod(abc))
print(np.size(abc))

150
11
63.0
378
[ 30  50 172 322 367 378]
[        30        600      73200   10980000  494100000 5435100000]
6


In [4]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price,"\n",quantity)
c = (np.cumprod([price,quantity], axis = 0))
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]
31270


Statistical Functions in Numpy🤗😒😍

In [15]:
import numpy as np
import statistics as stats

baked_food = [200,300,150,130,200,280,170,188]

a = np.array(baked_food)
print(np.mean(baked_food))  #sum of all the values/number of values
print(np.median(baked_food))  #central value after sorting
print(stats.mode(baked_food))
print(np.std(baked_food))
print(np.var(baked_food))

202.25
194.0
200
55.68157235567257
3100.4375
